spring:
  application:
    name: playbacklog

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

playbacklog:
  storage:
    baseDir: ${FILE_BASE_DIR:/tmp/playbacklog}
  batchSize: 100